development:
  adapter: mysql
  database: survey
  encoding: utf8
  user: root
  password: mohawk

production:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3
